### ISSUE TITLE
SSL connect not ok

### ISSUE THREAD

**Issue by dielume** [JimmyTai/esp8266-AWSIoT#3]
Hello Jimmy Tai,

I followed all your recommendations in your branch.
However, I can't connect. This is my Serial Log:

connected with SIRA, channel 8
dhcp client start...
...ip:192.168.1.30,mask:255.255.255.0,gw:192.168.1.1

WiFi Connected
try to connect to AWS IoT...
Attempting MQTT connection with id 1000-A0:20:A6:2D:8D:4A ...
please start sntp first !
ssl read time: 0
ssl read time: 0
ssl read time: 0
ssl read time: 0
ssl read time: 0
ssl read time: 0
ssl read time: 0
ssl read time: 0
ssl read time: 0
ssl read time: 0
ssl read time: 0
ssl read time: 0
ssl read time: 0
ssl read time: 0
ssl read time: 0
ssl read time: 0
ssl read time: 0
ssl read time: 0
ssl read time: 1
ssl read time: 0
ssl read time: 1
ssl read time: 319
SSL connect not ok
MQTT cannot connect
try to connect to AWS IoT...
Attempting MQTT connection with id 1000-A0:20:A6:2D:8D:4A ...
please start sntp first !
ssl read time: 0
ssl read time: 0
ssl read time: 0
ssl read time: 0
ssl read time: 0
ssl read time: 0
ssl read time: 0
ssl read time: 0
ssl read time: 0
ssl read time: 0
ssl read time: 0
ssl read time: 1
ssl read time: 0
ssl read time: 289
SSL connect not ok
MQTT cannot connect
try to connect to AWS IoT...

thanks in advance

**Comment by JimmyTai** [comment]
@dielume could you turn on ssl debug level and get more information.

**Comment by dielume** [comment]
@JimmyTai Thanks for your early reply this is my Serial log after enable core+ssl debug

csum 0x2d
v09f0c112
~ld
Pboot
sta config unchanged.state: 3 -> 5 (10)
add 0
aid 4
cnt 

connected with SIRA, channel 6
dhcp client start...
...ip:192.168.1.30,mask:255.255.255.0,gw:192.168.1.1
try to connect to AWS IoT...
Attempting MQTT connection with id ioTTestDevice-A0:20:A6:2D:8D:4A ...
:ref 1
please start sntp first !
State:	sending Client Hello (1)
:wr
:sent 123
:ww
ssl read time: 0
ssl read time: 0
ssl read time: 0
ssl read time: 0
ssl read time: 0
ssl read time: 0
ssl read time: 0
ssl read time: 0
ssl read time: 0
ssl read time: 0
ssl read time: 0
ssl read time: 0
ssl read time: 0
:rn 1460
:rch 1460, 1460
ssl read time: 2
:rch 2920, 117
:rd 5, 2920, 0
:rdi 1460, 5
ssl read time: 4
:rd 3032, 3037, 5
:rdi 1455, 1455
:c 1455, 1460, 3037
:rdi 1460, 1460
:c 1460, 1460, 1577
:rdi 117, 117
:c0 117, 117
State:	receiving Server Hello (2)
State:	receiving Certificate (11)
State:	receiving Certificate Request (13)
State:	receiving Server Hello Done (14)
State:	sending Certificate (11)
:wr
:sent 12
:rn 7
:ww
:rcl
:abort
State:	sending Client Key Exchange (16)
ssl read time: 295
SSL connect not ok
Alert: close notify
:ur 1
:del
MQTT cannot connect
try to connect to AWS IoT...
Attempting MQTT connection with id ioTTestDevice-A0:20:A6:2D:8D:4A ...
:ref 1
Fri Aug 25 18:38:33 2017

State:	sending Client Hello (1)
:wr
:sent 123
:ww
ssl read time: 0
ssl read time: 0
ssl read time: 0
ssl read time: 0
ssl read time: 0
ssl read time: 0
ssl read time: 0
:rn 1460
ssl read time: 1
:rch 1460, 1460
:rch 2920, 117
:rd 5, 1460, 0
:rdi 1460, 5
ssl read time: 5
:rd 3032, 3037, 5
:rdi 1455, 1455
:c 1455, 1460, 3037
:rdi 1460, 1460
:c 1460, 1460, 1577
:rdi 117, 117
:c0 117, 117
State:	receiving Server Hello (2)
State:	receiving Certificate (11)
State:	receiving Certificate Request (13)
State:	receiving Server Hello Done (14)
State:	sending Certificate (11)
:wr
:sent 12
:rn 7
:ww
:rcl
:abort
State:	sending Client Key Exchange (16)
ssl read time: 288
SSL connect not ok
Alert: close notify
:ur 1
:del



Thanks

**Comment by dielume** [comment]
@JimmyTai I solved the problem was a policy and a SPIFFS issue.
In the version 2.4.0-rc1, it can possible use tls v1.2. Just a suggestion
Thanks for all.
